version: '3.8'
services:
  database:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=timelog
      - POSTGRES_USER=root-user
      - POSTGRES_PASSWORD=root-pass
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  static:
  pgdata:
