version: '3.8'
services:
  database:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=timelog
      - POSTGRES_USER=root-user
      - POSTGRES_PASSWORD=root-pass
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root.
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database
    
volumes:
  static:
  pgdata:
  pgadmin_data:
